modLoader="javafml"
loaderVersion="[36,)"
license="Public domain"

[[mods]]
modId="canalsunblocked"
version="v1.0"
displayName="Canals Unblocked"
#updateJSONURL=""
displayURL="https://www.curseforge.com/minecraft/mc-mods/canals-unblocked"
#logoFile="logo.png"
#credits="credits"
authors="StephenBarnes"
description='''
Makes water flow further through 1-block-wide canals.'''

[[dependencies.canalsunblocked]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.canalsunblocked]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
