modLoader="javafml"
loaderVersion="[36,)"
license="Public domain"

[[mods]]
modId="canals"
version="v2.0"
displayName="Canals"
#updateJSONURL=""
displayURL="https://www.curseforge.com/minecraft/mc-mods/canals"
#logoFile="logo.png"
#credits="credits"
authors="StephenBarnes"
description='''
Let player construct canals to make fluids flow further.'''

[[dependencies.canals]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.canals]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
