modLoader="javafml"
loaderVersion="[36,)"
license="LGPL V3"

[[mods]]
modId="canals"
version="2.3"
displayName="Canals"
#updateJSONURL=""
displayURL="https://www.curseforge.com/minecraft/mc-mods/canals"
#logoFile="logo.png"
#credits="credits"
authors="StephenBarnes"
description='''
Construct canals to make fluids flow further.'''

[[dependencies.morewaterlogging]]
    modId="statement"
    mandatory=true
    versionRange="*"
    ordering="NONE"
    side="BOTH"

[[dependencies.canals]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.canals]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
